### ISSUE TITLE
Encode error with 2 video

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#25]
I meet error in encode (can't index file) step in spite of very fine in preview step

Example scripts
UNDER=LWLibavVideoSource("under.mkv.lwi")
OVER=LWLibavVideoSource("over.mkv.lwi").Lanczos4Resize(1920, 1080).Trim(1,13547).Crop(1730,70,-80,-950)

Overlay(UNDER, OVER, Y=70, X=1730, mode="blend", opacity=1.0)

**Comment by Asd-g** [comment]
Does the error persist if you run only the script with avsmeter/avsr?

**Comment by kedaitinh12** [comment]
> Does the error persist if you run only the script with avsmeter/avsr?

It's still in AvsPmod

**Comment by kedaitinh12** [comment]
And it's fine with preview of AvsPmod too

> Does the error persist if you run only the script with avsmeter/avsr?

Scripts only still fine in preview step of Megui, AvsPmod but in encode step, it got error in both Megui and AvsPmod

**Comment by Asd-g** [comment]
Did you try different encoder?

**Comment by kedaitinh12** [comment]
> Did you try different encoder?

Can you suggestions what encoders? I think error from index 2 video in this scripts. It will fine if only index 1 video in encode step

**Comment by Asd-g** [comment]
I mean if you use x264 vanilla encoder, you can try [x264 tmod](https://github.com/jpsdr/x264/releases) or any other non-vanilla version.

The same is valid for x265 too.

If you just run the script for the entire video with avsmeter64/avsr/avspmod/ffmpeg.. and there is no error, the thing to come in my mind is encoder issue because the avs scripts itself runs without errors.

Also try to replace `LWLibavVideoSource("under.mkv.lwi")` with `LWLibavVideoSource("source_vide", cachefile="under.mkv.lwi")`. Do the same with the other `LWLibavVideoSource` call.

**Comment by kedaitinh12** [comment]
I already use tmod. And after change .lwi to .mkv. Error was gone. Don't know LWLibavVideoSource can load video direct and don't need cachefile=".mkv.lwi"
