### ISSUE TITLE
LWLibavVideoSource ignores repeated frames from lagarith codec

### ISSUE THREAD

**Issue by isidroco** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#28]
Small sample of a lagarith still image 150 frames avi: https://www.mediafire.com/file/hwdf8075reip6ta/07_-_creditos.avi/file
VDUB2 will open .AVI frames 0-149
With AviSynthPlus_3.7.2_20220317_vcredist; DirectShowSource will open and extra frame: 0-150
L-SMASH-Works-20221109 LWLibavVideoSource will only open one frame: 0-0
( FFMpegSource2 also returns one frame ).  Is it possible to have a working source function with accurate seek?

This is simple script to test given AVI (same behaviour on MKV container):

```
# v= DirectShowSource( "07 - creditos.avi", ConvertFPS=true)
v= LWLibavVideoSource( "07 - creditos.avi")
return v

```

**Comment by Asd-g** [comment]
Thanks for the sample.

`ffmpeg -i "07_-_creditos.avi"` shows duration of 5 sec.
`ffprobe -count_frames -show_entries stream=nb_read_frames -i "07 - creditos.avi"` shows only one frame. That's why there is only one frame in the index file (*.lwi). You can report to ffmpeg to fix this.

Currently the workaround is:
```
v = LWLibavVideoSource( "07 - creditos.avi")
v = Loop(v, 150)
return v
```

**Comment by Asd-g** [comment]
This behavior wouldn't be [changed](https://trac.ffmpeg.org/ticket/10173#comment:1) (at least for ffmpeg based source filters).

If you want to use ffmpeg based source filters with lagarith you shouldn't enable null frames.
