### ISSUE TITLE
File plays with FFMS2 but not LWLibav

### ISSUE THREAD

**Issue by flossy83** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#53]
Please see my doom9 forum post here for details

https://forum.doom9.org/showthread.php?p=1994817#post1994817

Thank you

**Comment by Asd-g** [comment]
That sample you shared in doom9 has broken field flags at the end. The last frame marked as repeated is 40041.
The next frames are constructed from top field[n] + bottom field[n+1] (meaning top field first). (1)
Frames from 40041 to 40161 (including) are marked as Top field first.
Frame 40162 is marked as Bottom field first. Because of this and because of (1) the frame can't be created. If ffms2 is opening this file with `rffmode=1`, then you have luck that frame 40162 is at the end and it's black otherwise the frame will look weird.

Note: the frame numbers I use start counting from 1.

**Comment by flossy83** [comment]
Thanks.  

I guess the question is how tolerant of bad files do you want to be.

The reason the flags are probably broken is because that DVD puts all its episodes into a single DVD Title, so the only way of extracting individual episodes was to manually cut the Title into segments, which I did using ffmpeg. 

"c:\program files\ffmpeg\bin\ffmpeg.exe" -ss 00:00:00 -to 00:23:54 -i "C:\Title.mkv" -c copy -map 0 "C:\S01E01.mkv"

I guess doing that cut it at a spot where it shouldn't be cut and resulted in some broken field flags.

**Comment by Asd-g** [comment]
Yes, cutting few more frames are needed.
